### ISSUE TITLE
the user quits the room after some time and remote view is not set

### ISSUE THREAD

**Issue by YoussefHachicha** [codewithkael/WebrtcConference#1]
I have used the same server and the same code the only thing that have changed is the turn server
this is the [link](https://drive.google.com/file/d/12GRhtyCsaTxT8PA8ki8N9cEfgiYsgGgj/view?usp=sharing) that proves that

**Comment by YoussefHachicha** [comment]
I figured out that the issue is from the turn server

**Comment by sushantchauhan08** [comment]
Hi @YoussefHachicha not able to render the remote view. what can be the issue using the same codebase

**Comment by codewithkael** [comment]
> Hi @YoussefHachicha not able to render the remote view. what can be the issue using the same codebase

Its for sure the turn server

**Comment by YoussefHachicha** [comment]
@sushantchauhan08, like @codewithkael mentioned, it's probably an issue with the TURN server. You can try using Metered's TURN server to test if that’s the actual problem.
